### ISSUE TITLE
'hypar help <command>' would be easier to use than 'hypar <command> help'

### ISSUE THREAD

**Issue by hummingburd** [hypar-io/sdk#19]

**Comment by ikeough** [comment]
As discussed, this pattern for the CLI mimics other CLIs, notably `aws` and `dotnet`.

**Comment by vdubya** [comment]
@ikeough This package might be of use to you for implementing more flexible command line parsing: https://github.com/commandlineparser/commandline

**Comment by ikeough** [comment]
That's a good one. Thanks @vdubya. I had previously used `NDesk.Options` but it doesn't have support for dotnet core.
