### ISSUE TITLE
Rename "Execute" and "Executions" in Hypar CLI to "Run" and "Runs"(?) to match VS Code nomenclature

### ISSUE THREAD

**Issue by hummingburd** [hypar-io/sdk#23]

**Comment by ikeough** [comment]
I see where this would work for `hypar run`, but I'm not sure I agree with `hypar runs` (maybe it'll grow on me). The present naming of `execute` and `executions` is because a run of a function on Hypar is recorded as an `execution`.

**Comment by hummingburd** [comment]
Yeah, "hypar runs" kind of blows, that's why I threw in the question mark. I was actually think of "hypar results" but i didn't think that was accurate. "hypar runlog" ?

**Comment by ikeough** [comment]
I’m closing this issue as I don’t have plans to update the naming unless we update it across the system. In addition, the ability to list executions will probably be removed from the CLI leaving only “hypar execute.”
