### ISSUE TITLE
The Hypar Sdk should probably clone as "HyparSDK" not "sdk"

### ISSUE THREAD

**Issue by hummingburd** [hypar-io/sdk#46]
"sdk" is a little ambiguous. It would probably be helpful to developers if we branded it.

**Comment by hummingburd** [comment]
Incidentally, I seem unable to put labels on issues. Not sure if I'm missing something or if I need elevated permissions.

**Comment by ikeough** [comment]
Developers can clone this and call it whatever they want. I'm expecting that contributors to the SDK will be able to use `git clone` with a directory name argument to rename appropriately.
